name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:  # 添加手动触发的功能

env:
  IMAGE_NAME: nginxwebui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

        # 添加 Maven 或 Gradle 构建步骤 (以 Maven 为例)
      - name: 构建 Java 项目
        run: mvn clean package

      - name: 构建镜像
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: 登录到镜像仓库
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: echo $ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

      - name: 推送镜像
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 从 GitHub 事件负载中获取分支名
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # 对于 "master" 分支和标签，使用 "latest" 版本号
          VERSION=$(if [ "$BRANCH_NAME" == "master" ]; then echo "latest"; else echo $BRANCH_NAME; fi)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
