name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch:  # 添加手动触发的功能

env:
  IMAGE_NAME: nginxwebui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

      - name: 构建 Java 项目
        run: mvn clean package

      - name: 构建镜像
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: 登录到镜像仓库
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: echo $ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

      - name: 检查并重标已存在镜像
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}  # 将 run_number 传递给脚本
        run: |
          IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 从 GitHub 事件负载中获取分支名
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # 对于 "master" 分支和标签，使用 "latest" 版本号
          VERSION=$(if [ "$BRANCH_NAME" == "master" ]; then echo "latest"; else echo $BRANCH_NAME; fi)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          # Docker Hub API 检查是否已存在该标签
          EXISTING_TAG=$(docker manifest inspect $IMAGE_ID:$VERSION || true)

          # 如果该标签的镜像存在，先给它打上运行编号减一的标签
          if [ ! -z "$EXISTING_TAG" ]; then
            # 使用表达式计算 PREV_RUN_NUMBER
            PREV_RUN_NUMBER=$((GITHUB_RUN_NUMBER - 1))
            echo "Tagging the existing image with run number: $PREV_RUN_NUMBER"
            docker tag $IMAGE_ID:$VERSION $IMAGE_ID:$PREV_RUN_NUMBER
            docker push $IMAGE_ID:$PREV_RUN_NUMBER
          fi

      - name: 推送新的镜像
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_ID=$DOCKER_USERNAME/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 获取分支名
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # 根据分支名确定版本号
          VERSION=$(if [ "$BRANCH_NAME" == "master" ]; then echo "latest"; else echo $BRANCH_NAME; fi)

          # 推送新的版本标签镜像
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
